Tests/Resources/dash-folder/EmbeddedJavascriptFile-With-Dashes.js, Tests/ResourcesLoading.cs, Tests/Tests.csproj, Tests/Tests.csproj.user, WebViewControl/ResourcesManager.cs, WebViewControl/WebViewControl.nuspec
Add configuration to run unit tests
Fix nuspec CefSharp version
=> Fix error when loading resources in paths with dashes

ReactViewControl/ReactViewRender.cs, Tests/CommonTests.cs, WebViewControl/Listener.cs, WebViewControl/WebView.cs
Allow configuring cache path and cache persistence
=> Fixed events multiple subscriptions

ViewGenerator/ViewGenerator.nuspec
To enable linter on Service Studio projects:
- Merge this PR.
- Generate Nuget package of ViewGenerator and put it on OS nuget repo.
- Manage nuget packages on SS and put the new version of ViewGenerator
=> Updated ViewGenerator.nuspec

NuGet.config, ReactViewControl/build.cake, ReactViewControl/build.ps1, ReactViewControl/config.json, ReactViewResources/build.cake, ReactViewResources/build.ps1, ReactViewResources/config.json, ViewGenerator/build.cake, ViewGenerator/build.ps1, ViewGenerator/config.json, ViewGeneratorCore/build.cake, ViewGeneratorCore/build.ps1, ViewGeneratorCore/config.json, ViewPacker/build.cake, ViewPacker/build.ps1, ViewPacker/config.json, WebViewControl/build.cake, WebViewControl/build.ps1, WebViewControl/config.json, authenticate.py
Pipelines created in azure devops
=> pipelines for each package in azure devops

ViewGenerator/build/ViewGenerator.targets, ViewGenerator/tools/webpack/Plugins/CommonConfiguration.ts, ViewGenerator/tools/webpack/Plugins/Utils.ts, ViewGenerator/tools/webpack/webpack_workers.config.ts
Adding webpack configs to support workers and also adding a configuration for Monaco
=> Webpack monaco

ViewGenerator/ViewGenerator.nuspec, ViewGenerator/build/ViewGenerator.targets, ViewGeneratorCore/ViewGeneratorCore.nuspec, ViewGeneratorCore/build/ViewGeneratorCore.targets
Several changes to the target files to support incremental builds
=> Build time

WebViewControl/AssemblyCache.cs, WebViewControl/ResourcesManager.cs, WebViewControl/WebView.CefRequestHandler.cs, WebViewControl/WebView.CefResourceRequestHandler.cs, WebViewControl/WebView.cs, WebViewControl/WebViewControl.csproj
Still have to use locks (maybe discuss this offline) on the ResourcesManager view cache
=> Move cache to Resources Manager

WebViewControl/AssemblyCache.cs, WebViewControl/ResourceUrl.cs, WebViewControl/ResourcesManager.cs, WebViewControl/WebView.CefResourceRequestHandler.cs
expose GetEmbeddedResourceAssemblyName
=> Assembly cache

ViewGenerator/ViewGenerator.csproj, ViewGenerator/ViewGenerator.nuspec, ViewGenerator/build/ViewGenerator.targets
Allow to define a folder (CleanFilesExcludePath) where the clean of js and css files is ignored.
Default path is Legacy/
=> Build exclude folder

.gitignore, Example/Example.csproj, Example/ExampleView/ExampleView.scss, Example/ExampleView/ExampleView.tsx, Example/packages.config, ViewGenerator/ViewGenerator.nuspec, ViewGenerator/tools/webpack/Rules/Sass.ts, ViewGenerator/tools/webpack/webpack_stylesheets.config.ts, ViewPacker/ViewPacker.nuspec, ViewPacker/tools/package-lock.json, ViewPacker/tools/package.json
**Goal:** Enable to share stylish values from CSS to JS.
**Outcome:** 
- A single source of truth between CSS and JS;
- Cheaper to maintain;
- Enable themes for JS components, i.e., Monaco Editor;
=> Enable SASS variables in JS

ViewGenerator/ViewGenerator.nuspec, ViewGenerator/build/ViewGenerator.targets, ViewGenerator/tools/webpack/Plugins/CommonConfiguration.ts, ViewGenerator/tools/webpack/Rules/Files.ts, ViewGenerator/tools/webpack/webpack_plugins.config.ts, ViewGenerator/tools/webpack/webpack_stylesheets.config.ts, ViewGenerator/tools/webpack/webpack_views.config.ts
- Also fixed problems when assembly name is different than the project directory name being compiled.
=> Fixed webpack compilation with symlinks

Example.Avalonia/Example.Avalonia.csproj, Example.Avalonia/ExampleView/DefaultStyleSheetWithBorders.scss, Example.Avalonia/ExtendedReactView.cs, Example.Avalonia/ExtendedReactViewFactory.cs, Example.Avalonia/MainWindow.xaml, Example.Avalonia/MainWindow.xaml.cs, Example.Avalonia/Settings.cs, Example/Example.csproj, Example/ExampleView/DefaultStyleSheetWithBorders.scss, Example/ExtendedReactView.cs, Example/ExtendedReactViewFactory.cs, Example/ReactViewExample.xaml, Example/ReactViewExample.xaml.cs, Example/Settings.cs, ReactViewControl.Avalonia/ReactViewControl.Avalonia.csproj, ReactViewControl.Avalonia/ReactViewControl.nuspec, ReactViewControl/ReactView.cs, ReactViewControl/ReactViewRender.LoaderModule.cs, ReactViewControl/ReactViewRender.cs, ReactViewResources/Loader/Loader.ts, Tests.ReactView/DefaultStylesheetLoadTests.cs, Tests.ReactView/TestAppView/Default_2.scss, Tests.ReactView/Tests.ReactView.csproj
=> Enable set DefaultStyleSheet (cef)

.gitignore, SampleWebView.Avalonia/App.xaml, SampleWebView.Avalonia/MainWindow.xaml, SampleWebView.Avalonia/MainWindow.xaml.cs, SampleWebView.Avalonia/MainWindowViewModel.cs, SampleWebView.Avalonia/Program.cs, SampleWebView.Avalonia/SampleWebView.Avalonia.csproj, WebViewControl.Avalonia/WebView.Avalonia.cs
Made some improvements to the Avalonia demo.
=> Improve avalonia demo

WebViewControl.Avalonia/WebViewControl.Avalonia.csproj, WebViewControl/WebView.cs
I think the changes I made are obvious so I don't think I need to add any description. Also if needed I may revert all changes made in WebView.Control.Avalonia.csproj,i made them because I cant build it in any other way.Also, I'm not sure what is better, to add all properties from CefSettings to WebView class or just to add method which will have CefSettings as argument, just made it in the way it was previously done
Will close #175
=> Add ability to configure UserAgent

WebViewControl.Avalonia/WebViewControl.Avalonia.csproj, WebViewControl/WebViewControl.csproj
Create a new release with the new CefGlue version
=> Version bump 2.85.37 → 2.85.38

WebViewControl.Avalonia/WebViewControl.Avalonia.csproj, WebViewControl/WebViewControl.csproj
=> Update CefGlue to 91.4472.4 (version bump 2.91.5)

WebViewControl.Avalonia/WebViewControl.Avalonia.csproj
With increased MaxDepth serialization
=> RMAC-9065 - Upgrade cefglue version

WebViewControl/Request.cs
=> Exposed access to the CefRequest header methods

Directory.Packages.props, WebViewControl.Avalonia/WebViewControl.Avalonia.csproj
=> Bump CefGlue to a version that preserves object references on Serialization

Directory.Build.props, Nuget.config, WebViewControl/WebView.InternalRequestHandler.cs
CEF 117.2.4+g5053a95+chromium-117.0.5938.150 upgrade
=> 117.2.4+g5053a95+chromium-117.0.5938.150

Directory.Build.props
Pending CefGlue PR approval and version release
=> Upgrade CEF to 120.1.8+ge6b45b0+chromium-120.0.6099.109

Directory.Build.props, SampleWebView.Avalonia/MainWindow.xaml.cs, WebViewControl/GlobalSettings.cs, WebViewControl/WebView.cs, WebViewControl/WebViewControl.csproj, tests/Tests.WebView/App.xaml.cs
Disable OSR by default , as there's lots of people complaining about OSR issues
=> Disable OSR by default
